# Copyright 2015 Adobe
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
# Based on a version by Louis Dionne

shallow_clone: true

build:
  verbosity: detailed

configuration:
  - Debug
platform:
  - x64

branches:
  except:
    - /pr\/.+/

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps


  ############################################################################
  # Install a recent CMake
  ############################################################################
  # - set CMAKE_URL="https://cmake.org/files/v3.14/cmake-3.14.4-win32-x86.zip"
  # - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  # - 7z x cmake.zip -oC:\projects\deps > nul
  # - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  # - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

environment:
  matrix:
    - FLAVOR: Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_TOOLSET: Visual Studio 15 2017 Win64
      BOOST_ROOT: C:\Libraries\boost_1_69_0

    - FLAVOR: Visual Studio 2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_TOOLSET: Visual Studio 16 2019
      BOOST_ROOT: C:\Libraries\boost_1_71_0

build_script:
  - cd C:\projects\libraries
  - IF EXIST build RMDIR /S /Q build
  - MKDIR build
  - cd build
  - cmake -G "%CMAKE_TOOLSET%" -D BOOST_ROOT="%BOOST_ROOT%" -D Boost_USE_STATIC_LIBS=ON ..
  - cmake --build . --config Release
  - ctest -C Release
