# Copyright 2015 Adobe
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
# Based on a version by Louis Dionne

shallow_clone: true

os:
  - Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Debug

branches:
  except:
    - /pr\/.+/

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Python
  ############################################################################
  - set PYTHON_URL="https://www.python.org/ftp/python/3.6.2/python-3.6.2-embed-amd64.zip"
  - appveyor DownloadFile %PYTHON_URL% -FileName python.zip
  - 7z x python.zip -oC:\projects\deps\python > nul
  - set PATH=C:\projects\deps\python;%PATH%
  - python --version

  ############################################################################
  # Install conan
  ############################################################################
  - pip install conan


  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\libraries


build_script:
  - setup_msvc_debug.bat
  - cd build_debug
  - cmake --build .
  - bin\stlab.test.future.test --log_level=message
  - bin\stlab.test.serial_queue.test.exe
