# Copyright 2015 Adobe
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
# Based on a version by Louis Dionne

shallow_clone: true

image: Visual Studio 2015

build:
  verbosity: detailed

configuration:
  - Release

branches:
  except:
    - /pr\/.+/

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  #- mkdir C:\projects\deps
  #- cd C:\projects\deps


  ############################################################################
  # Install a recent CMake
  ############################################################################
  #- set CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.6-win64-x64.zip"
  #- appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  #- 7z x cmake.zip -oC:\projects\deps > nul
  #- move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  #- set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\libraries

build_script:
  - IF EXIST build RMDIR /S /Q build
  - MKDIR build
  - cd build
  - cmake -G "Visual Studio 14 Win64" -DBOOST_ROOT=C:/Libraries/boost_1_63_0 -D stlab_testing=ON ..
  - cmake  --build .
  - test\Release\stlab.test.future.test --log_level=message
  - test\Release\stlab.test.serial_queue.test.exe
  - test\Release\stlab.test.task.test.exe
  - test\Release\stlab.test.tuple.test.exe
