sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.conan

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
        key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  
osx_image: xcode8

env:
  - build_type=debug options="-D stlab_testing=ON"
  - build_type=release options="-D stlab_testing=ON"

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        build_type=debug
        coverage=TRUE
        options="-D stlab_testing=ON -D coverage=ON"
      packages:
        - lcov
      after_success:
        - cd build
        - bash <(curl -s https://codecov.io/bash) -X fix

    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=address;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=undefined;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        TSAN_OPTIONS="suppressions=${TRAVIS_BUILD_DIR}/test/sanitizer_suppressions"
        flags="-fsanitize=thread;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"

    - os: linux
      compiler: clang
      env:
        build_type=debug
        options="-D stlab_testing=ON"
      before_install:
        - pip install --user conan
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
              key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - clang-3.8
            - cmake
            - cmake-data
        coverity_scan:
          project:
            name: "stlab/libraries"
            description: "Build submitted via Travis CI"
          notification_email: fosterb@gmail.com
          build_command_prepend: ""
          build_command: ".travis/build.sh"
          branch_pattern: coverity

  exclude:
    - os: osx
      compiler: gcc

branches:
  except: /pr\/.*/
  
before_install:
  - pip install --user conan
  
script:
  - .travis/build.sh
  
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: wVoguAsrN2FIKS3TyxQeg0SvIySuaUu1lRgO1KQBoOeLOBUedNy90futkLyPVMs1snK3M2aq6iMW5OqWRq/GdKXbfjFTpiUcObolq7tOXaXwwCAUufC+tCYpQqzZaKbw2lhWqTd4xd/GzmupRBEVeW3pKPR/avLCLUq/uJtz2MvAOFE6u0uvIPqvIgaEPq8tQ5qPNn8oTiU7uozqXk+/aQxMoj/W+mK6r/U8ISQM8DNRJy1k+WadfPfarTH21rJgfsZbWoKHjhxc5ysk+VPnTu7gg1rBcSu2Q/91LNQTSUBGNvd+bjyQ55zaCjZOsz832AmIOjy06OtpvvYbeJRtw+saJv44LTbwjiIwyAUCnPB0D9pnyA5NIdBOsGNuwWuyBrtawzbum71tdAjW/PpMgm5vT5ouLWWw9+0zk0nR0E3fxY0KodUKz8Ct6qwwtt3HfcD1Q1NU1wBOzfAROOi3CeazOOpbsLC///ysuxhIkJBd068b+/EUSyEuQNUkMJj8EC2DxNtsZrk6/tihnATbdWb4o/0D2t0MqGsYmOPeWAtaTyeOkr9nLYxSbwC94mu8YmNN9A9/FJKd0Pa0IKACLvgup0sAXLOJjPEfvYz1s8WQBAlCe03NOS/9eOrSXv2nKFw/YiMinBUEqQfrucwV7vfD0m2LsE1S+u4N5ozqw48=
